/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "block.h"

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

void
gluster_block_cli_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		blockCreateCli block_create_cli_1_arg;
		blockListCli block_list_cli_1_arg;
		blockInfoCli block_info_cli_1_arg;
		blockDeleteCli block_delete_cli_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case BLOCK_CREATE_CLI:
		_xdr_argument = (xdrproc_t) xdr_blockCreateCli;
		_xdr_result = (xdrproc_t) xdr_blockResponse;
		local = (char *(*)(char *, struct svc_req *)) block_create_cli_1_svc;
		break;

	case BLOCK_LIST_CLI:
		_xdr_argument = (xdrproc_t) xdr_blockListCli;
		_xdr_result = (xdrproc_t) xdr_blockResponse;
		local = (char *(*)(char *, struct svc_req *)) block_list_cli_1_svc;
		break;

	case BLOCK_INFO_CLI:
		_xdr_argument = (xdrproc_t) xdr_blockInfoCli;
		_xdr_result = (xdrproc_t) xdr_blockResponse;
		local = (char *(*)(char *, struct svc_req *)) block_info_cli_1_svc;
		break;

	case BLOCK_DELETE_CLI:
		_xdr_argument = (xdrproc_t) xdr_blockDeleteCli;
		_xdr_result = (xdrproc_t) xdr_blockResponse;
		local = (char *(*)(char *, struct svc_req *)) block_delete_cli_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

void
gluster_block_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		blockCreate block_create_1_arg;
		blockDelete block_delete_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case BLOCK_CREATE:
		_xdr_argument = (xdrproc_t) xdr_blockCreate;
		_xdr_result = (xdrproc_t) xdr_blockResponse;
		local = (char *(*)(char *, struct svc_req *)) block_create_1_svc;
		break;

	case BLOCK_DELETE:
		_xdr_argument = (xdrproc_t) xdr_blockDelete;
		_xdr_result = (xdrproc_t) xdr_blockResponse;
		local = (char *(*)(char *, struct svc_req *)) block_delete_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}
