---
# tasks file for initiator

- import_tasks: install.yml
- import_tasks: service.yml

- name: set multipath
  command: "{{ item }}"
  with_items:
    - modprobe dm_multipath
    - mpathconf --enable

- name: append the multipath.conf file
  blockinfile:
    dest: /etc/multipath.conf
    block: |
      # LIO iSCSI
      devices {
          device {
              vendor "LIO-ORG"
              user_friendly_names "yes" # names like mpatha
              path_grouping_policy "failover" # one path per group
              path_selector "round-robin 0"
              failback immediate
              path_checker "tur"
              prio "const"
              no_path_retry 120
              rr_weight "uniform"
          }
      }
    backup: yes

- name: Reload multipath daemon
  systemd:
    name: multipathd
    state: reloaded
