.TH gluster-block 8 "command line utility" " 26 Feb 2017" "Red Hat, Inc."
.PP


.SH NAME
gluster-block - Gluster Block Storage Console Manager (command line utility)
.PP


.SH SYNOPSIS
.B gluster-block
[\fBtimeout <seconds>\fR]
<\fBcreate|list|info|delete|modify|replace|genconfig\fR>
<\fBvolname\fR[\fB/blockname\fR]>
[\fB<args>\fR]
[\fB--json*\fR]
.PP


.SH DESCRIPTION
The Gluster Block Storage Console Manager(\fBgluster-block\fR) is a CLI utility, which aims at making gluster backed block storage creation and maintenance as simple as possible.

Note that the gluster-blockd daemon is responsible for block management, hence the daemon must be running on all servers.
.PP


.SH COMMANDS
.SS
\fBcreate\fR <VOLNAME/NEW-BLOCKNAME> [ha <COUNT>] [auth <enable|disable>] [prealloc <full|no>] [storage <filename>] [ring-buffer <size-in-MB-units>] [block-size <size-in-Byte-units>] [io-timeout <N in Second>] <HOST1[,HOST2,..]> [BYTES]
create block device.
.TP
[ha <COUNT>]
multipath requirement for high availability (default: 1)
.TP
[auth <enable|disable>]
authentication setting (default: disable)
.TP
[prealloc <full|no>]
"full" mode preallocates space by writing zeros to storage (default: full)
.TP
[storage <filename>]
existing file(only name) in the gluster volume, that needs to be linked while creating block (default: creates a new file)
.TP
[ring-buffer <size-in-MB-units>]
kernel ring buffer size for exchanging iSCSI commands, range [1MB - 1024MB] (default: as per kernel)
.TP
[block-size <size-in-Byte-units>]
kernel hw block size, aligns to 512 (default: as per kernel)
.TP
[io-timeout <N in Second>]
time duration for which the tcmu-runner waits to check if the IO from gluster block hosting volume server is responsive. Ideally this value should be kept larger than both IO timeout value (default is 30s) in the iscsi client/initiator side and the gluster ping timeout (default is 42s), (default: 43s)

.TP
<HOST1,[HOST2....]>
servers in the pool where targets will be exported
.TP
[BYTES]
size in B|KiB|MiB|GiB|TiB|PiB ... (default: bytes)
.PP

.SS
\fBlist\fR <VOLNAME>
list available block devices.
.PP

.SS
\fBinfo\fR <VOLNAME/BLOCKNAME>
details about block device.
.PP

.SS
\fBdelete\fR <VOLNAME/BLOCKNAME> [unlink-storage <yes|no>] [force]
delete block device.
.TP
[unlink-storage <yes|no>]
unlink the backend file from gluster volume (default: yes)
.PP

.SS
\fBmodify\fR <VOLNAME/BLOCKNAME> [<auth enable|disable>] [size <size> [force]]
modify block device.
.TP
[<auth enable|disable>]
modify authentication on the device
.TP
[size <size> [force]]
modify size of the device
.PP

.SS
\fBreplace\fR <VOLNAME/BLOCKNAME> <old-node> <new-node> [force]
replace block device.
.PP

.SS
\fBreload\fR <volname/blockname> [force]
reload a block device.
.PP

.SS
\fBgenconfig\fR <VOLNAME1[,VOLNAME2,VOLNAME3,...]> enable-tpg <host>
generate the block volumes target configuration.
.TP
enable-tpg <host>
specify the active path node
.PP

.SS
.BR help
show help message and exit.
.PP

.SS
.BR version
show version info and exit.
.PP

.SH COMMON CLI OPTIONS
.SS
[\fBtimeout <seconds>\fR]
it is the time in seconds that cli can wait for daemon to respond (default: 300)
.PP

.SS
[\fB--json*\fR]
used to request the output result in json format (default: plain text) and supported JSON formats: --json|--json-plain|--json-spaced|--json-pretty
.PP

.SH EXAMPLES
.nf
To create a block device of size 1GiB
.B # gluster-block create blockVol/sampleBlock ${HOST} 1GiB

To create a block device of size 1GiB with timeout 300 seconds
.B # gluster-block timeout 300 create blockVol/sampleBlock ${HOST} 1GiB

To create a block device of size 1GiB with auth enable
.B # gluster-block create blockVol/sampleBlock auth enable ${HOST} 1GiB

To create a block device of size 1GiB, by preallocating storage with zero fill
.B # gluster-block create blockVol/sampleBlock prealloc full ${HOST} 1GiB

To create a thinly-provisioned block device of size 1GiB
.B # gluster-block create blockVol/sampleBlock prealloc no ${HOST} 1GiB

To create a block device with existing file in blockVol
.B # gluster-block create blockVol/sampleBlock storage 3c242959-9238-4ce0-a1ed-19086aa23c7b ${HOST}

To create a block device with ring buffer size 16MiB
.B # gluster-block create blockVol/sampleBlock ring-buffer 16 ${HOST} 1GiB

To create a block device with block size 1024
.B # gluster-block create blockVol/sampleBlock block-size 1024 ${HOST} 1GiB

To create a block device of size 1GiB with multi-path(replica) 3
.B # gluster-block create blockVol/sampleBlock ha 3 ${HOST1},${HOST2},${HOST3} 1GiB

To create a block device of size 1GiB and expect response in json format
.B # gluster-block create blockVol/sampleBlock ${HOST} 1GiB --json

To disable auth on a block device
.B # gluster-block modify blockVol/sampleBlock auth disable

To enable auth on a block device
.B # gluster-block modify blockVol/sampleBlock auth enable

To resize an existing block device sampleBlock of size 1GiB to new size 2GiB
.B # gluster-block modify blockVol/sampleBlock size 2GiB

To list available block devices
.B # gluster-block list blockVol

To get details of a block device
.B # gluster-block info blockVol/sampleBlock

To delete a block device
.B # gluster-block delete blockVol/sampleBlock

To delete a block device, but let backend file persist in blockVol(for later use)
.B # gluster-block delete blockVol/sampleBlock unlink-storage no

To replace a block device from ${NODE1} to ${NODE2}
.B # gluster-block replace blockVol/sampleBlock ${NODE1} ${NODE2}

To reload a block device in all the HA nodes
.B # gluster-block reload blockVol/sampleBlock

To simply generate the block volumes target configuration.
.B # gluster-block genconfig blockVol1[,blockVol2,blockVol3,...] enable-tpg ${HOST} | tee new_saveconfig.json

To generate the block volumes target configuration and load it
.B # mv /etc/target/saveconfig.json /etc/target/saveconfig.json.bak
.B # gluster-block genconfig blockVol1[,blockVol2,blockVol3,...] enable-tpg ${HOST} | tee /etc/target/saveconfig.json
.B # systemctl restart gluster-blockd tcmu-runner
.fi
.PP

.SH FILES
/var/log/gluster-block/*
.br
/var/run/gluster-block.socket
.br
/var/run/gluster-block.lock
.br
/etc/sysconfig/gluster-blockd
.br
/etc/logrotate.d/gluster-block
.PP


.SH REPORTING BUGS
Report bugs via gluster-devel <gluster-devel@gluster.org
.br
or <https://github.com/gluster/gluster-block/issues>


.SH AUTHOR
Prasanna Kumar Kalever <prasanna.kalever@redhat.com>

.SH THANKS
Vijay Bellur <vbellur@redhat.com>
.br
Pranith Kumar Karampuri <pkarampu@redhat.com>



.SH SEE ALSO
.nf
\fBgluster-blockd\fR(8), \fBtargetcli\fR(8), \fBtcmu-runner\fR(8), \fBglusterfs\fR(8), \fBglusterd\fR(8), \fBgluster\fR(8)
.fi
.PP


.SH COPYRIGHT
.nf
Copyright (c) 2016 Red Hat, Inc. <http://www.redhat.com>
.PP
